name: build

on:
  push:
    branches: [ build ]
  pull_request:
    branches: [ build ]

jobs:
  build_linux:
    #if: ${{ false }}  # disable for now
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: "diffmerge"
    - name: apt update
      run: |
        sudo apt update
    - name: Install gtk lib
      run: |
        sudo apt install libgtk-3-dev
    - name: Install uuid lib
      run: |
        sudo apt install uuid-dev
    - name: Install lintian
      run: |
        sudo apt install lintian
    - name: Build
      run: |
        cd diffmerge/sgdm3
        BUILDNUM=${{github.run_number}} CSID=${{github.sha}} make -f ./Makefile.Linux
    - uses: actions/upload-artifact@v4
      with:
        name: diffmerge_5.0.0.${{github.run_number}}.dev_amd64.deb
        if-no-files-found: error
        path: diffmerge/builds/Linux/x86_64/Release/diffmerge_5.0.0.${{github.run_number}}.dev_amd64.deb

  build_mac:
    #if: ${{ false }}  # disable for now
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: "diffmerge"
    - name: Build arm64
      run: |
        cd diffmerge/sgdm3
        BUILDNUM=${{github.run_number}} CSID=${{github.sha}} ARCH=arm64 make -f ./Makefile.Apple
    - uses: actions/upload-artifact@v4
      with:
        name: DiffMerge.5.0.0.${{github.run_number}}.arm64.dev.dmg
        if-no-files-found: error
        path: diffmerge/builds/Apple/arm64/Release/DiffMerge.5.0.0.${{github.run_number}}.arm64.dev.dmg
    - name: Build x86_64
      run: |
        cd diffmerge/sgdm3
        BUILDNUM=${{github.run_number}} CSID=${{github.sha}} ARCH=x86_64 make -f ./Makefile.Apple
    - uses: actions/upload-artifact@v4
      with:
        name: DiffMerge.5.0.0.${{github.run_number}}.x86_64.dev.dmg
        if-no-files-found: error
        path: diffmerge/builds/Apple/x86_64/Release/DiffMerge.5.0.0.${{github.run_number}}.x64.dev.dmg

  build_windows_x86:
    #if: ${{ false }}  # disable for now
    runs-on: windows-2022

    defaults:
      run:
        shell: bash

    steps:
    - name: rm link
      run: |
        rm /usr/bin/link

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: "diffmerge"

    - name: Configure build for x86
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86

    - name: Build
      run: |
        cd diffmerge/sgdm3
        BUILDNUM=${{github.run_number}} CSID=${{github.sha}} TARGET_PLATFORM=x86 make -f Makefile.Windows

    - uses: actions/upload-artifact@v4
      with:
        name: DiffMerge_5.0.0.${{github.run_number}}.dev_x86.msi
        if-no-files-found: error
        path: diffmerge/builds/Windows/i686/Release/DiffMerge_5.0.0.${{github.run_number}}.dev_x86.msi

    - uses: actions/upload-artifact@v4
      with:
        name: DiffMerge_5_0_0_${{github.run_number}}_dev_x86.zip
        if-no-files-found: error
        path: diffmerge/builds/Windows/i686/Release/DiffMerge_5_0_0_${{github.run_number}}_dev_x86.zip

  build_windows_x64:
    #if: ${{ false }}  # disable for now
    runs-on: windows-2022

    defaults:
      run:
        shell: bash

    steps:
    - name: rm link
      run: |
        rm /usr/bin/link

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: "diffmerge"

    - name: Configure build for x64
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Build
      run: |
        cd diffmerge/sgdm3
        BUILDNUM=${{github.run_number}} CSID=${{github.sha}} TARGET_PLATFORM=x64 make -f Makefile.Windows

    - uses: actions/upload-artifact@v4
      with:
        name: DiffMerge_5.0.0.${{github.run_number}}.dev_x64.msi
        if-no-files-found: error
        path: diffmerge/builds/Windows/amd64/Release/DiffMerge_5.0.0.${{github.run_number}}.dev_x64.msi

    - uses: actions/upload-artifact@v4
      with:
        name: DiffMerge_5_0_0_${{github.run_number}}_dev_x64.zip
        if-no-files-found: error
        path: diffmerge/builds/Windows/amd64/Release/DiffMerge_5_0_0_${{github.run_number}}_dev_x64.zip


